version: "2"

services:
  state-machines:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: state-machines
    command: tail -F keepalive
    # environment:
    #   SOME VAR: wow
    volumes:
      - ./server:/opt/state-machines/server
    ports:
      - "80:80"
