version: "2"

services:
  state-machines:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: state-machines
    command: uvicorn --reload --workers 1 --host 0.0.0.0 --port 80 main:app
    depends_on:
      - postgres
    # environment:
    #   SOME VAR: wow
    volumes:
      - ./server:/opt/state-machines/server
    ports:
      - "80:80"

  # Infrastructure
  postgres:
    image: postgres:11.5
    container_name: statemachines-postgres
    environment:
      POSTGRES_DB: statemachines
      POSTGRES_USER: admin
      DB: statemachines
      DBHOST: "127.0.0.1"
      DBPASS: ""
      DBUSER: postgres
    ports:
      - "5432:5432"
